name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      REV:
        description: 'Kernel Revision (example: 3)'
        required: false
      STRINGS:
        description: 'Kernel Strings (example: MyKernel)'
        required: true
        default: 'MyKernel'
      KERNELSU_BRANCH:
        description: 'KernelSU branch (ignore if no ksu)'
        required: true
        default: stable
        type: choice
        options:
        - stable
        - dev
      KERNELSU_SUPPORT:
        description: 'KernelSU support'
        required: true
        type: boolean
      USE_PERMISSIVE:
        description: 'SELinux Permissive'
        required: true
        type: boolean
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: android_kernel_samsung_a12s
        fetch-depth: 0
    - name: Prepare dependencies
      run: |
        sudo apt update -y
        sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl curl lz4 -y
        sudo aptitude install libssl-dev -y
    - name: Build with Clang
      run: |
        export IS_CI="y"
        export GIT_REVISION=$REV_INPUT
        export GIT_LOCALVERSION=$LOCALVERSION_INPUT
        export KSU_BRANCH=$KERNELSU_BRANCH_INPUT
        export KSU_STATE=$KERNELSU_STATE_INPUT
        export SELINUX_STATE=$SELINUX_STATE_INPUT
        bash $(pwd)/build.sh
      env:
        REV_INPUT: ${{ github.event.inputs.REV }}
        LOCALVERSION_INPUT: ${{ github.event.inputs.STRINGS }}
        KERNELSU_BRANCH_INPUT: ${{ github.event.inputs.KERNELSU_BRANCH }}
        KERNELSU_STATE_INPUT: ${{ github.event.inputs.KERNELSU_SUPPORT }}
        SELINUX_STATE_INPUT: ${{ github.event.inputs.USE_PERMISSIVE }}
      working-directory: android_kernel_samsung_a12s
    - name: Upload the files
      uses: actions/upload-artifact@v4.3.1
      with:
        name: kernel_files
        path: |
          android_kernel_samsung_a12s/rsuntk/*.img
          android_kernel_samsung_a12s/rsuntk/*.tar
          android_kernel_samsung_a12s/rsuntk/readme.txt
