name: Build Multiple Kernel

on:
  workflow_dispatch:
    inputs:
      REV:
        description: 'Kernel Revision (ex: 3)'
        required: false
      STRINGS:
        description: 'Kernel Strings (ex: MyKernel)'
        required: true
        default: 'MyKernel'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: android_kernel_samsung_a12s
        fetch-depth: 0
    - name: Prepare dependencies
      run: |
        sudo apt update -y
        sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl curl -y
        sudo aptitude install libssl-dev -y
    - name: Build with Clang
      run: |
        export REV=$REV_INPUT
        export LOCALVERSION=$LOCALVERSION_INPUT
        bash $(pwd)/ci_script/build_multiple.sh
      env:
        REV_INPUT: ${{ github.event.inputs.REV }}
        LOCALVERSION_INPUT: ${{ github.event.inputs.STRINGS }}
      working-directory: android_kernel_samsung_a12s
    - name: Upload to Files
      uses: actions/upload-artifact@v4
      with:
        name: Kernelfiles
        path: | 
          android_kernel_samsung_a12s/rsuntk/*.img
          android_kernel_samsung_a12s/rsuntk/*.tar
          android_kernel_samsung_a12s/rsuntk/*.txt
